/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface lightmapperConstants {
  public final static int LM_FALSE = lightmapperJNI.LM_FALSE_get();
  public final static int LM_TRUE = lightmapperJNI.LM_TRUE_get();
  public final static int LM_NONE = lightmapperJNI.LM_NONE_get();
  public final static int LM_ALL_CHANNELS = lightmapperJNI.LM_ALL_CHANNELS_get();
}
